### ISSUE TITLE
New comment on https://yanirseroussi.com/2023/04/21/remaining-relevant-as-a-small-language-model/

### ISSUE THREAD

**Issue by CHEWJ** [yanirs/yanirseroussi.com#4]
Reading of the despair of the many silent/invisible contributors of intellectual property copied, without financial recompense, which went into these LLMs. It's a training data gold rush/free for all right now, just as unedifying and thoughtless as actual gold rushes in history were. I fear this will also quickly lead to Apple-style closed gardens of proprietary creative talent (think of top artists, writers and thinkers signed up to train AI rather than creating content for direct human consumption). Counter-ML tech like Glaze will only delay the inevitable. https://glaze.cs.uchicago.edu/#:~:text=Glaze%20is%20a%20tool%20to,community%2C%20most%20notably%20Karla%20Ortiz.

I can think of some ways where governments might respond, e.g. special taxes and incentives on AI businesses to fund creative academies and collectives, much as public universities are today.

**Comment by yanirs** [comment]
Thanks John! Yeah, I doubt that tech like Glaze can be made future proof, as they admit on that page. Besides, I lean more towards the view that [all creative work is derivative](https://www.youtube.com/watch?v=jcvd5JZkUXY) and [copying isn't theft](https://www.youtube.com/watch?v=IeTybKL1pM4). Copyright mostly protects platforms and businesses rather than individuals. While I empathise with individuals who feel like their work is being exploited without their permission, I don't see the training of machine learning models as being that different from artists learning from other artists.

Thoughtful government intervention would be great, but it's unlikely to be applied in a timely manner or evenly across jurisdictions.
